#!/bin/bash

docker build --build-arg OPENTOFU_VERSION=$OPENTOFU_VERSION --build-arg TERRAGRUNT_VERSION=$TERRAGRUNT_VERSION  --build-arg TERRAFORM_DOCS_VERSION=latest --build-arg TFLINT_VERSION=latest --build-arg TRIVY_VERSION=latest  --build-arg INSTALL_ALL=false -f $DOCKERFILE_PATH -t $IMAGE_NAME .
